<?php
session_start();
require_once '../lib/fpdf.php';
require_once '../auth/db_config.php'; // adjust if your DB connection file is elsewhere

// Check if user is logged in using user_id
if (!isset($_SESSION['user_id'])) {
    header("Location: ../auth/login.php");
    exit();
}

$user_id = $_SESSION['user_id'];

// Fetch tenant details from the database
$stmt = $conn->prepare("SELECT full_name, email, phone FROM users WHERE id = ?");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die("No user found.");
}

$user = $result->fetch_assoc();
$conn->close();

// Create PDF document
class PDF extends FPDF {
    function Header() {
        // Logo
        $this->Image('../assets/logo.png', 10, 8, 20); // Ensure your logo path is correct
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'Mojo Electrical Enterprise', 0, 1, 'C');
        $this->SetFont('Arial', 'I', 12);
        $this->Cell(0, 10, '"Reliability in Electrical Services"', 0, 1, 'C');
        $this->Ln(10);
        $this->SetDrawColor(255, 204, 0); // Yellow underline
        $this->Line(10, 35, 200, 35);
        $this->Ln(10);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 9);
        $this->SetTextColor(128);
        $this->Cell(0, 10, 'Generated by Mojo Electrical Enterprise - ' . date("Y-m-d"), 0, 0, 'C');
    }
}

//  Initialize and generate the PDF
$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);

// Title
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Tenant Information Document', 0, 1, 'C');
$pdf->Ln(10);

// Tenant Details
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(40, 10, 'Full Name:', 0, 0);
$pdf->Cell(100, 10, $user['full_name'], 0, 1);

$pdf->Cell(40, 10, 'Email:', 0, 0);
$pdf->Cell(100, 10, $user['email'], 0, 1);

$pdf->Cell(40, 10, 'Phone:', 0, 0);
$pdf->Cell(100, 10, $user['phone'], 0, 1);

$pdf->Ln(10);
$pdf->MultiCell(0, 10, "This document confirms the tenant's registration under Mojo Electrical Enterprise. All information is verified and confidential. Please contact Mojo Electrical Enterprise for any clarifications or service requests.");

// Signature Area
$pdf->Ln(20);
$pdf->Cell(0, 10, '_____________________________', 0, 1, 'R');
$pdf->Cell(0, 10, 'Authorized Signatory', 0, 1, 'R');

//  Output PDF file for download
$pdf->Output('D', 'Tenant_Document_' . $user['full_name'] . '.pdf');
exit;
?>
