<?php
ob_start(); // Prevent any unwanted output before PDF headers
session_start();
require_once '../lib/fpdf.php';
require_once '../auth/db_config.php'; // Adjust path if needed

// Ensure user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: ../auth/login.php");
    exit();
}

$user_id = $_SESSION['user_id'];

// Fetch tenant details
$stmt = $conn->prepare("SELECT full_name, email, phone FROM users WHERE id = ?");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die("No user found.");
}

$user = $result->fetch_assoc();
$conn->close();

// PDF Class
class PDF extends FPDF {
    function Header() {
        $logoPath = __DIR__ . '/../assets/logo.png';
        if (file_exists($logoPath)) {
            $this->Image($logoPath, 10, 8, 20);
        }

        // Company Info
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'Mojo Enterprise', 0, 1, 'C');
        $this->SetFont('Arial', 'I', 12);
        $this->Cell(0, 10, '"Convenience in Apartment Systems"', 0, 1, 'C');
        $this->Ln(10);
        $this->SetDrawColor(255, 204, 0); // Yellow underline
        $this->Line(10, 35, 200, 35);
        $this->Ln(10);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 9);
        $this->SetTextColor(128);
        $this->Cell(0, 10, 'Generated by Mojo  Enterprise - ' . date("Y-m-d"), 0, 0, 'C');
    }
}

// Initialize PDF
$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);

// Tenant info header (top-right)
$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 5, 'Date: ' . date("F j, Y"), 0, 1, 'R');
$pdf->Cell(0, 5, 'Tenant: ' . ($user['full_name'] ?? 'Tenant'), 0, 1, 'R');
$pdf->Ln(10);

// Title
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Tenant Information & Rental Agreement Notice', 0, 1, 'C');
$pdf->Ln(8);

// Tenant details
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(40, 10, 'Full Name:', 0, 0);
$pdf->Cell(100, 10, $user['full_name'], 0, 1);

$pdf->Cell(40, 10, 'Email:', 0, 0);
$pdf->Cell(100, 10, $user['email'], 0, 1);

$pdf->Cell(40, 10, 'Phone:', 0, 0);
$pdf->Cell(100, 10, $user['phone'], 0, 1);
$pdf->Ln(8);

// Notice content
$pdf->MultiCell(0, 10, 
"Dear " . ($user['full_name'] ?? 'Tenant') . ",\n
Welcome to Mojo Enterprise Apartments! We are delighted to have you as a potential tenant.

To confirm your tenancy, an *initial deposit of KES 30,000* is required upon signing. This deposit secures your apartment and will be adjusted or refunded in accordance with our tenancy policy.

After your initial payment, you will be expected to make *monthly rent payments of approximately KES 80,000* on or before the 5th day of each month.

Below are key tenancy rules and guidelines to ensure a comfortable and respectful living environment for all tenants:
 i).Rent must be paid on time to avoid penalties.  
 ii).Noise levels should be kept minimal after 10:00 PM.  
 iii).Tenants are responsible for maintaining cleanliness within their premises.  
 iv).Any maintenance or repair issues should be reported to management promptly.  
 v).Unauthorized subletting of units is strictly prohibited.  
 vi).Pets are allowed only upon approval from management.  
 vii).Electricity and water bills should be cleared monthly.  
 vii).Damage to property due to negligence will be charged to the tenant.  

By proceeding with your registration, you acknowledge that you have read, understood, and agreed to these terms and conditions. For any inquiries or clarifications, please contact the management through our official channels.

We look forward to a great stay with you at Mojo  Enterprise Apartments.");

// Signature Area
$pdf->Ln(20);
$pdf->Cell(0, 10, '_', 0, 1, 'R');
$pdf->Cell(0, 10, 'Authorized Signatory', 0, 1, 'R');

// Safe file name
$tenantName = $user['full_name'] ?? 'Tenant';
$fileName = 'Tenant_Document_' . preg_replace('/\s+/', '_', $tenantName) . '.pdf';
$savePath = __DIR__ . '/../tenant_docs/' . $fileName;

// Ensure folder exists
if (!is_dir(__DIR__ . '/../tenant_docs')) {
    mkdir(__DIR__ . '/../tenant_docs', 0777, true);
}

// Save a copy in the server
$pdf->Output('F', $savePath);

// Clear output buffer (prevent FPDF header error)
ob_end_clean();

// Send PDF for download
$pdf->Output('D', $fileName);
exit;
?>
